//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Page_Info
    {
        public decimal Info_ID { get; set; }
        public string FileName { get; set; }
        public string FileTitle { get; set; }
        public string Remarks { get; set; }
    }
}
