//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TeamsApprove
    {
        public decimal ID { get; set; }
        public string Team_ID { get; set; }
        public string Team_NAME { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public string Note { get; set; }
        public int ID_subscription { get; set; }
        public string subscription { get; set; }
        public string Subscription_ { get; set; }
    }
}
