//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Payment_Member
    {
        public decimal Subscriptions_ID { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<int> Subscriptions_Eyare { get; set; }
        public Nullable<decimal> ID_subscription { get; set; }
        public Nullable<decimal> subscription { get; set; }
        public Nullable<bool> PaymentY_N { get; set; }
        public string Note { get; set; }
        public string WhoInsert { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string WhoUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string WhoDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PaymentReceiptPath { get; set; }
        public string Member_ID { get; set; }
        public string Full_Name { get; set; }
        public string Phone { get; set; }
        public string Team_NAME { get; set; }
        public string Team_ID { get; set; }
    }
}
