//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Club_DatabaseEntities : DbContext
    {
        public Club_DatabaseEntities()
            : base("name=Club_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_Booking_Details> Table_Booking_Details { get; set; }
        public DbSet<Table_Contests> Table_Contests { get; set; }
        public DbSet<Table_Expenses> Table_Expenses { get; set; }
        public DbSet<Table_Master_Member> Table_Master_Member { get; set; }
        public DbSet<Table_Member_Details> Table_Member_Details { get; set; }
        public DbSet<Table_Teams> Table_Teams { get; set; }
        public DbSet<Table_User_Pages> Table_User_Pages { get; set; }
        public DbSet<Table_User_Profile> Table_User_Profile { get; set; }
        public DbSet<Table_User_Teams> Table_User_Teams { get; set; }
        public DbSet<Table_History_Contests> Table_History_Contests { get; set; }
    }
}
