//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Club_DatabaseEntities1 : DbContext
    {
        public Club_DatabaseEntities1()
            : base("name=Club_DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_Booking_Details> Table_Booking_Details { get; set; }
        public DbSet<Table_Contests> Table_Contests { get; set; }
        public DbSet<Table_Expenses> Table_Expenses { get; set; }
        public DbSet<Table_Master_Member> Table_Master_Member { get; set; }
        public DbSet<Table_Member_Details> Table_Member_Details { get; set; }
        public DbSet<Table_Teams> Table_Teams { get; set; }
        public DbSet<Table_User_Pages> Table_User_Pages { get; set; }
        public DbSet<Table_User_Profile> Table_User_Profile { get; set; }
        public DbSet<Table_User_Teams> Table_User_Teams { get; set; }
        public DbSet<Table_History_Contests> Table_History_Contests { get; set; }
    
        public virtual int SP_New_Team(string action, Nullable<decimal> iD, string team_ID, string team_NAME, Nullable<System.DateTime> joining_Date, string note)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(decimal));
    
            var team_IDParameter = team_ID != null ?
                new ObjectParameter("Team_ID", team_ID) :
                new ObjectParameter("Team_ID", typeof(string));
    
            var team_NAMEParameter = team_NAME != null ?
                new ObjectParameter("Team_NAME", team_NAME) :
                new ObjectParameter("Team_NAME", typeof(string));
    
            var joining_DateParameter = joining_Date.HasValue ?
                new ObjectParameter("Joining_Date", joining_Date) :
                new ObjectParameter("Joining_Date", typeof(System.DateTime));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_New_Team", actionParameter, iDParameter, team_IDParameter, team_NAMEParameter, joining_DateParameter, noteParameter);
        }
    }
}
