//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Booking_Details
    {
        public decimal ID { get; set; }
        public string Teams_ID { get; set; }
        public string Phone { get; set; }
        public string Booking_Date { get; set; }
        public string WhoInsert { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string WhoUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string WhoDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> RecordDelete { get; set; }
        public string Notes { get; set; }
    }
}
