//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Member_Details
    {
        public decimal ID { get; set; }
        public decimal Member_ID { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Datefrom { get; set; }
        public Nullable<System.DateTime> Dateto { get; set; }
        public string PicUrl { get; set; }
        public string Member_Type { get; set; }
        public string PicUrl1 { get; set; }
    }
}
