//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_History_Contests
    {
        public decimal ID { get; set; }
        public Nullable<decimal> Year { get; set; }
        public decimal Contests_ID { get; set; }
        public string Member_ID { get; set; }
        public string Team_ID { get; set; }
        public string Notes { get; set; }
    }
}
