//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User_Profile
    {
        public decimal ID { get; set; }
        public string Member_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public bool Lock_Account { get; set; }
        public bool InActive { get; set; }
    }
}
