//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dima__Wataeen__Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Master_MembeByApp
    {
        public decimal ID { get; set; }
        public string JobName { get; set; }
        public string Team_NAME { get; set; }
        public string Subscription { get; set; }
        public string Member_ID { get; set; }
        public string Full_Name { get; set; }
        public string Address { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<System.DateTime> Date_Birth { get; set; }
        public string Phone { get; set; }
        public string Team_ID { get; set; }
        public string Member_Type { get; set; }
        public Nullable<decimal> Card_ID_ON { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public string WhoInsert { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string WhoUpdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string WhoDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<decimal> ID_subscription { get; set; }
        public string PicUrl { get; set; }
        public Nullable<bool> ReturnY_N { get; set; }
        public string Expr1 { get; set; }
    }
}
